#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
export _VNC_INSTALL_ROOT=$SCRIPT_DIR


source $SCRIPT_DIR/../settings.sh 






function cleanup {
   rm -f $vnc_start_file
   if [[ ${_D+defined} ]];then
       $C_CMD /opt/TurboVNC/bin/vncserver -kill :$_D 2>/dev/null 
       rm -f  /tmp/.X11-unix/X$_D
       rm -f  /tmp/.X$_D-lock
   fi
   running=$($C_CMD /opt/TurboVNC/bin/vncserver -list | grep "^:" )
   while IFS= read -r r; do
       rr=($r)
   done <<< "$running"
   extra_pids=($(ps -u $USER | grep Xvnc | awk '{ print $1 }'))
   #Possible that the lock file has not been created
   for p in ${extra_pids[@]};do
       grep "$_VNC_SHELL_ID" /proc/$p/environ &> /dev/null && kill -9 $p 2>/dev/null
   done


   kill -1 $novnc_pp &>/dev/null
   kill -1 $novnc_p &>/dev/null
   kill $(jobs -p) &>/dev/null
   exit 1
}

function _msg {
    echo -e "$1"
}


POSITIONAL=()
while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
    --debug)
      keep_log_file=1
      shift
      ;;
    --no-wm)
      nowm=1
      shift
      ;;
    --help|-h)
      echo -e "Usage: start-vnc [OPTIONS]
Tool to start VNC server and print out connection information.
Uses turbovnc and novnc. By default will start the fluxbox window manager 

Options:
    -h, --help      Show this message and exit

    --debug         Save novnc output to log file

    --no-wm         Don't start the window manager 

" 
      exit 0
      ;;
    *)    # unknown option
      POSITIONAL+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done

if [[ ${keep_log_file+defined} ]];then
    NOVNC_LOG=novnc.log
else
    NOVNC_LOG=/dev/null
fi

_MOUNTS=$HOME,/var/spool,/tmp,/tmp:/run,$PWD,$_VNC_INSTALL_ROOT
_PASS=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 8 ; echo '')
_VNC_CONTAINER=$SCRIPT_DIR/vnc.sif
_STARTUP_FILE=$SCRIPT_DIR/xstartup.turbovnc
if [[ ! -e "$_VNC_CONTAINER" ]]; then
    echo "FATAL (internal error):  Could not find vnc base container" 
    exit 1
elif [[ ! -e "$_STARTUP_FILE" ]];then
    echo "FATAL (internal error):  Could not find xstartup.turbovnc" 
    exit 1
fi

C_CMD="singularity --silent exec -B $_MOUNTS $_VNC_CONTAINER"
trap cleanup EXIT INT

_msg "StartTime: $(date +"%Y-%m-%dT%H:%M:%S")"
_msg "Generating password"
mkdir -p  ~/.vnc/
chmod og-rwx ~/.vnc/
chgrp $USER ~/.vnc/
echo "$_PASS" | $C_CMD /opt/TurboVNC/bin/vncpasswd -f > ~/.vnc/passwd || {  echo "FATAL (internal error): password generation failed"; exit 1 ;} 
chmod og-rwx ~/.vnc/passwd
chgrp $USER ~/.vnc/passwd
_msg "Starting vnc server"

vnc_start_file=$(mktemp /tmp/vnc_start.XXXXXX)
if [[ ${nowm+defined} ]];then
    $C_CMD /opt/TurboVNC/bin/vncserver -noxstartup 2> $vnc_start_file
else
    $C_CMD /opt/TurboVNC/bin/vncserver -xstartup $_STARTUP_FILE  2> $vnc_start_file
fi


_D=$( grep Desk $vnc_start_file  | cut -d ":" -f4)
if [[ -z "$_D" ]];then
    _msg "Vnc server failed to start"
    cat $vnc_start_file
    exit 1
fi
_P=$( grep "VNC conn" $(grep "Log file" $vnc_start_file | cut -d " " -f4) | rev | cut -d " " -f1 | rev)
_msg  "\tVnc server running on display :$_D"
_msg  "\tVnc port: $_P"

if [[ ${keep_log_file+defined} ]];then
    _msg "=====DEBUG=========="
    cat $vnc_start_file
    _msg "===================="
fi
rm $vnc_start_file



export DISPLAY=":$_D"

timeout=$VNC_TIMEOUT
wait_time=0
pause_time=1


_msg "Starting novnc proxy ( ${timeout}sec timeout )"
$C_CMD /opt/noVNC/utils/novnc_proxy --vnc localhost:$_P --listen $_HN:0 &> $NOVNC_LOG & 
novnc_pp=$!
if [[ ${keep_log_file+defined} ]];then
   _msg  "\tNovnc log saved to $NOVNC_LOG"
fi



export novnc_p=""
while [[ -z "$novnc_p" || "$(echo "$novnc_p" | wc -l)" -gt 1  ]]; do
    sleep $pause_time
    wait_time=$((wait_time + pause_time))
    export novnc_p=$(pgrep -P $(pgrep -P $novnc_pp) 2>/dev/null)
    if [[ $wait_time -gt $timeout ]];then
        _msg "Timeout waiting for novnc proxy to start"
        exit 1
    fi 
    ps -p $novnc_pp &>/dev/null || { echo "Novnc exit unexpectedly" ; exit 1 ;}
done
# novnc does not display the port correctly when passed 0 as the port number
# so we need to find it out. 
wait_time=0
_msg "Resolving novnc proxy port ( ${timeout}sec timeout)"
function getPortForPid {                                                               
    inode=$(ls -l /proc/$1/fd/* | grep -o socket.* | grep -o  "[0-9]*")                
    portHex=$(cat /proc/net/tcp | grep $inode | awk '{print $2}' | cut -d ":" -f2 )    
    echo $((16#$portHex))                                                              
}                                                                                      
                                                                                       
export _VNC_PORT=$( getPortForPid $novnc_p  2>/dev/null )                              
while [[ -z "$_VNC_PORT"  ]];do                                                        
    sleep $pause_time                                                                  
    wait_time=$((wait_time + pause_time))                                              
    export _VNC_PORT=$( getPortForPid $novnc_p )                                       
    if [[ $wait_time -gt $timeout ]];then
        _msg "Failed to resolve port for novnc proxy"
        exit 1
    fi 
    ps -p $novnc_pp &>/dev/null || { echo "Novnc exit unexpectedly" ; exit 1 ;}
done

_msg  "\tNovnc proxy on port: $_VNC_PORT"

_msg  "\n\nCONNECT WITH BROWSER
==================
Run on local machine to forward vnc connection from ${SUPERCOMPUTER^} to local computer, if the port is in use locally change the port 
    ssh -N -L $_VNC_PORT:$_HN:$_VNC_PORT $_JUMP_HOST $_TARGET_HOST
Connect to this url in browser on local machine after running , port needs to be the same as in the ssh command (left value)
    http://localhost:$_VNC_PORT/vnc.html?password=$_PASS
=================="

_msg  "\nCONNECT WITH VNC CLIENT
==================
Run on local machine to forward vnc connection from ${SUPERCOMPUTER^} to local computer, if the port is in use locally change the port (left value)
    ssh -N -L $_P:$_HN:$_P $_JUMP_HOST $_TARGET_HOST
Connect with native (locally installed) vnc client, e.g TigerVNC
    vncviewer localhost:$_P
When prompted for a password, use $_PASS
=================="

wait 
